---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-1-config
data:
  HOSTNAME: app-1
  ENVIRONMENT: dev
  PLATFORM: kubernetes
  LOG_LEVEL: debug
  PORT: "80"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-2-config
data:
  HOSTNAME: app-2
  ENVIRONMENT: dev
  PLATFORM: kubernetes
  LOG_LEVEL: debug
  PORT: "8080"