apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.name }}
    spec:
      containers:
      {{- range .Values.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
          {{- range .ports }}
            - containerPort: {{ . }}
          {{- end }}
        {{- if .env }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
        {{- end }}
        {{- if .configMapRef }}
          envFrom:
            - configMapRef:
                name: {{ .configMapRef }}
        {{- end }}
      {{- end }}
