apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: helm
    #chartPath: ./
    releaseName: helm-dev
    namespace: helm
    #valuesFile: values.yaml

configMapGenerator:
  - name: app-1-config
    envs:
      - ./files/app-1.env
