replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent
  ports:
    containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetProtocol: http
  protocol: TCP
  name: http

ingress:
  host: helm.mydomain.com
  root:
      backend: 
      port: 443
      path: /
