replicaCount: 1

containers:
  - name: app-1
    image: nginxdemos/hello:latest
    imagePullPolicy: IfNotPresent
    ports:
      containerPort: 80
    configMapRef: app-1-config

  - name: app-2
    image: jenkins/jenkins:lts
    imagePullPolicy: IfNotPresent
    ports:
      containerPort: 8080
    configMapRef: app-2-config

service:
  name: helm-service-1
  type: ClusterIP
  ports:
    - name: app-1
      port: 80
      targetPort: 80
    - name: app-2
      port: 8080
      targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: helm.mydomain.com
      paths:
        - path: /(/|$)(.*)
          pathType: ImplementationSpecific
          service:
            name: helm-service-1
            port: 80
        - path: /auth(/|$)(.*)
          pathType: ImplementationSpecific
          service:
            name: helm-service-1
            port: 8080
